/* SPDX-FileCopyrightText: 2026 Blender Authors
 *
 * SPDX-License-Identifier: GPL-2.0-or-later */

#include "testing/testing.h"

#include "BKE_gtest_base.hh"
#include "BKE_idprop.hh"
#include "BKE_image.hh"
#include "BKE_main.hh"
#include "BKE_material.hh"
#include "BKE_node.hh"
#include "BKE_node_legacy_types.hh"
#include "BKE_node_runtime.hh"
#include "BKE_paint.hh"
#include "BKE_paint_material_composite.hh"
#include "BKE_paint_material_layer_edit.hh"
#include "BKE_paint_material_mask_bake.hh"

#include "BLI_index_range.hh"
#include "BLI_listbase.h"
#include "BLI_rect.h"
#include "BLI_uuid.h"
#include "BLI_vector.hh"

#include "DNA_image_types.h"
#include "DNA_material_types.h"
#include "DNA_node_types.h"
#include "DNA_scene_types.h"

#include "IMB_imbuf.hh"
#include "IMB_imbuf_types.hh"

#include <cstring>

#include "paint_material_layer_edit_intern.hh"
#include "paint_material_layer_idprops.hh"
#include "paint_material_layer_mask_bake_intern.hh"

namespace blender::bke::tests {

class PaintMaterialLayerMaskBakeTest : public bke::BlenderGTestBase {
 public:
  Main *bmain = nullptr;
  Material *material = nullptr;
  Vector<ImBuf *> owned_buffers;

  void SetUp() override
  {
    bmain = BKE_main_new();
    material = add_material_with_principled("Material");
  }

  void TearDown() override
  {
    for (ImBuf *ibuf : owned_buffers) {
      IMB_freeImBuf(ibuf);
    }
    owned_buffers.clear();
    /* Before the main: the cache holds partial-update subscriptions created from these images. */
    BKE_paint_material_mask_bake_cache_free_all();
    BKE_main_free(bmain);
  }

  /** A generated byte image, the storage the composite layers name. */
  Image *add_image(const char *name, const int image_size = 4)
  {
    const float color[4] = {0.0f, 0.0f, 0.0f, 1.0f};
    return BKE_image_add_generated(bmain,
                                   image_size,
                                   image_size,
                                   name,
                                   32,
                                   false,
                                   IMA_GENTYPE_BLANK,
                                   color,
                                   false,
                                   true,
                                   false);
  }

  /** Overwrite every pixel of \a image with one RGBA value. */
  void fill_image(Image &image, const uchar r, const uchar g, const uchar b, const uchar a)
  {
    void *lock = nullptr;
    ImBuf *ibuf = BKE_image_acquire_ibuf(&image, nullptr, &lock);
    ASSERT_NE(ibuf, nullptr);
    uchar *pixels = ibuf->byte_data_for_write();
    for (const int64_t i : IndexRange(int64_t(ibuf->x) * ibuf->y)) {
      pixels[i * 4 + 0] = r;
      pixels[i * 4 + 1] = g;
      pixels[i * 4 + 2] = b;
      pixels[i * 4 + 3] = a;
    }
    BKE_image_release_ibuf(&image, ibuf, lock);
  }

  /** A byte RGBA destination buffer of \a image_size square, owned by the fixture. */
  ImBuf *add_output_buffer(const int image_size = 4)
  {
    ImBuf *ibuf = IMB_allocImBuf(uint(image_size), uint(image_size), ImBufFlags::ByteData);
    ibuf->channels = 4;
    owned_buffers.append(ibuf);
    return ibuf;
  }

  Material *add_material_with_principled(const char *name)
  {
    Material *ma = BKE_material_add(bmain, name);
    bNodeTree &tree = *ma->nodetree;
    bNode *principled = bke::node_add_static_node(nullptr, tree, SH_NODE_BSDF_PRINCIPLED);
    bNode *output = bke::node_add_static_node(nullptr, tree, SH_NODE_OUTPUT_MATERIAL);
    bke::node_add_link(tree,
                       *principled,
                       *bke::node_find_socket(*principled, SOCK_OUT, "BSDF"_ustr),
                       *output,
                       *bke::node_find_socket(*output, SOCK_IN, "Surface"_ustr));
    return ma;
  }

  bNodeTree &tree()
  {
    return *material->nodetree;
  }

  bNode *add_math()
  {
    return bke::node_add_static_node(nullptr, tree(), SH_NODE_MATH);
  }

  /** A fresh input socket to play the coverage role. */
  bNodeSocket *add_coverage(bNode **r_node = nullptr)
  {
    bNode *node = add_math();
    if (r_node != nullptr) {
      *r_node = node;
    }
    return static_cast<bNodeSocket *>(BLI_findlink(&node->inputs, 0));
  }

  /** Wire \a source's first output into \a coverage, the live chain shape a bake replaces. */
  void feed_coverage(bNode &source, bNode &coverage_node, bNodeSocket &coverage)
  {
    bke::node_add_link(tree(),
                       source,
                       *static_cast<bNodeSocket *>(source.outputs.first),
                       coverage_node,
                       coverage);
  }

  MaskBakeAnchor create(const bNodeSocket &coverage, const bUUID &marker, const int channel)
  {
    MaskBakeAnchor anchor;
    EXPECT_TRUE(mask_bake_anchor_create(*bmain, tree(), coverage, marker, channel, 8, 8, anchor));
    tree().ensure_topology_cache();
    return anchor;
  }

  /** The row a real edit leaves baked: its B, its row marker and its mask correction's identity. */
  struct BakedRow {
    Image *baked = nullptr;
    bUUID row_marker = {};
    bUUID correction = {};
  };

  BakedRow build_baked_row()
  {
    BakedRow row;
    PaintMaterialLayerAddParams params;
    params.image_size = 8;
    PaintMaterialLayerEditError error = PaintMaterialLayerEditError::None;
    EXPECT_TRUE(BKE_paint_material_layer_add(*bmain, *material, params, nullptr, &error));
    EXPECT_TRUE(BKE_paint_material_layer_add(*bmain, *material, params, nullptr, &error));
    EXPECT_TRUE(BKE_paint_material_layer_correction_add(*bmain,
                                                        *material,
                                                        1,
                                                        PaintMaterialCorrectionSection::Mask,
                                                        PaintMaterialCorrectionEffect::Paint,
                                                        "M",
                                                        &row.correction,
                                                        &error));
    for (Image &image : bmain->images) {
      if (image.paint_layer_channel == PAINT_LAYER_MAP_MASK_BAKED) {
        row.baked = &image;
      }
    }
    EXPECT_NE(row.baked, nullptr);
    if (row.baked != nullptr) {
      row.row_marker = row.baked->paint_layer_id;
    }
    return row;
  }

  /** The map of the correction \a correction: the mask role its image carries. */
  Image *correction_image(const bUUID &correction)
  {
    for (Image &image : bmain->images) {
      if (image.paint_layer_channel == PAINT_LAYER_MAP_MASK &&
          BLI_uuid_equal(image.paint_layer_id, correction))
      {
        return &image;
      }
    }
    return nullptr;
  }

  /** The Mix node the correction \a correction owns. */
  bNode *correction_node(const bUUID &correction)
  {
    for (bNode &node : tree().nodes) {
      if (bke::paint_layer::node_is_correction(node) &&
          BLI_uuid_equal(bke::paint_layer::marker_get(node), correction))
      {
        return &node;
      }
    }
    return nullptr;
  }

  /** Overwrite \a rect of \a image *and record the edit*, as the paint path does. */
  void paint_region(Image &image, const rcti &rect, const uchar value)
  {
    void *lock = nullptr;
    ImBuf *ibuf = BKE_image_acquire_ibuf(&image, nullptr, &lock);
    ASSERT_NE(ibuf, nullptr);
    uchar *pixels = ibuf->byte_data_for_write();
    for (const int y : IndexRange(rect.ymin, BLI_rcti_size_y(&rect))) {
      for (const int x : IndexRange(rect.xmin, BLI_rcti_size_x(&rect))) {
        uchar *p = pixels + (int64_t(y) * ibuf->x + x) * 4;
        p[0] = p[1] = p[2] = value;
        p[3] = 255;
      }
    }
    BKE_image_partial_update_mark_region(
        &image, static_cast<ImageTile *>(image.tiles.first), ibuf, &rect);
    BKE_image_release_ibuf(&image, ibuf, lock);
  }

  void read_pixel(Image &image, const int x, const int y, uchar r_pixel[4])
  {
    void *lock = nullptr;
    ImBuf *ibuf = BKE_image_acquire_ibuf(&image, nullptr, &lock);
    ASSERT_NE(ibuf, nullptr);
    memcpy(r_pixel, ibuf->byte_data() + (int64_t(y) * ibuf->x + x) * 4, 4);
    BKE_image_release_ibuf(&image, ibuf, lock);
  }
};

TEST_F(PaintMaterialLayerMaskBakeTest, anchor_create_stamps_marker_channel_and_leaves_output_dead)
{
  const bUUID marker = BLI_uuid_generate_random();
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;
  bNodeSocket *coverage = add_coverage();
  MaskBakeAnchor anchor = create(*coverage, marker, channel);

  ASSERT_NE(anchor.node, nullptr);
  ASSERT_NE(anchor.live_input, nullptr);
  ASSERT_NE(anchor.image, nullptr);
  ASSERT_NE(anchor.image_node, nullptr);
  EXPECT_TRUE(BLI_uuid_equal(bke::paint_layer::marker_get(*anchor.node), marker));

  const IDProperty *channel_prop = IDP_GetPropertyTypeFromGroup(
      anchor.node->prop, MASK_BAKE_CHANNEL_PROP, IDP_INT);
  ASSERT_NE(channel_prop, nullptr);
  EXPECT_EQ(IDP_int_get(channel_prop), channel);

  bNodeSocket *result = bke::node_find_socket(*anchor.node, SOCK_OUT, "Result_Float"_ustr);
  ASSERT_NE(result, nullptr);
  EXPECT_TRUE(result->directly_linked_links().is_empty());
  EXPECT_TRUE(result->directly_linked_sockets().is_empty());
}

TEST_F(PaintMaterialLayerMaskBakeTest, anchor_create_parks_chain_top_and_leaves_output_dead)
{
  const bUUID marker = BLI_uuid_generate_random();
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;
  bNode *source = add_math();
  bNode *coverage_node = nullptr;
  bNodeSocket *coverage = add_coverage(&coverage_node);
  feed_coverage(*source, *coverage_node, *coverage);
  tree().ensure_topology_cache();

  MaskBakeAnchor anchor = create(*coverage, marker, channel);

  bNodeLink *coverage_link = sole_link_into(*coverage);
  ASSERT_NE(coverage_link, nullptr);
  EXPECT_EQ(coverage_link->fromnode, anchor.image_node);

  bNodeLink *live_link = sole_link_into(*anchor.live_input);
  ASSERT_NE(live_link, nullptr);
  EXPECT_EQ(live_link->fromnode, source);

  bNodeSocket *result = bke::node_find_socket(*anchor.node, SOCK_OUT, "Result_Float"_ustr);
  ASSERT_NE(result, nullptr);
  EXPECT_TRUE(result->directly_linked_links().is_empty());
}

TEST_F(PaintMaterialLayerMaskBakeTest, anchor_read_recovers_anchor)
{
  const bUUID marker = BLI_uuid_generate_random();
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;
  bNode *source = add_math();
  bNode *coverage_node = nullptr;
  bNodeSocket *coverage = add_coverage(&coverage_node);
  feed_coverage(*source, *coverage_node, *coverage);
  MaskBakeAnchor created = create(*coverage, marker, channel);

  MaskBakeAnchor read;
  ASSERT_TRUE(mask_bake_anchor_read(tree(), marker, channel, read));
  EXPECT_EQ(read.node, created.node);
  EXPECT_EQ(read.live_input, created.live_input);
  EXPECT_EQ(read.image, created.image);
  EXPECT_EQ(read.image_node, created.image_node);
  EXPECT_TRUE(BLI_uuid_equal(read.image->paint_layer_id, marker));
  EXPECT_EQ(read.image->paint_layer_channel, PAINT_LAYER_MAP_MASK_BAKED);
}

TEST_F(PaintMaterialLayerMaskBakeTest, baked_image_is_tagged_and_found_by_coverage)
{
  const bUUID marker = BLI_uuid_generate_random();
  const int channel = PAINT_MATERIAL_CHANNEL_ROUGHNESS;
  bNodeSocket *coverage = add_coverage();
  MaskBakeAnchor anchor = create(*coverage, marker, channel);

  Image *image = nullptr;
  bNode *image_node = nullptr;
  ASSERT_TRUE(mask_bake_coverage_is_baked(*coverage, image, image_node));
  EXPECT_EQ(image, anchor.image);
  EXPECT_EQ(image_node, anchor.image_node);
  EXPECT_EQ(image->paint_layer_channel, PAINT_LAYER_MAP_MASK_BAKED);
  EXPECT_TRUE(BLI_uuid_equal(image->paint_layer_id, marker));
}

TEST_F(PaintMaterialLayerMaskBakeTest, live_top_socket_returns_anchor_input_when_baked)
{
  const bUUID marker = BLI_uuid_generate_random();
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;
  bNode *source = add_math();
  bNode *coverage_node = nullptr;
  bNodeSocket *coverage = add_coverage(&coverage_node);
  feed_coverage(*source, *coverage_node, *coverage);
  MaskBakeAnchor anchor = create(*coverage, marker, channel);

  EXPECT_EQ(mask_bake_live_top_socket(*coverage), anchor.live_input);
}

TEST_F(PaintMaterialLayerMaskBakeTest, live_top_socket_falls_back_when_not_baked)
{
  bNodeSocket *coverage = add_coverage();
  tree().ensure_topology_cache();

  const bNodeSocket *live = mask_bake_live_top_socket(*coverage);
  EXPECT_EQ(live, coverage);
}

TEST_F(PaintMaterialLayerMaskBakeTest, anchor_remove_frees_owned_generated_image)
{
  const bUUID marker = BLI_uuid_generate_random();
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;
  bNodeSocket *coverage = add_coverage();
  MaskBakeAnchor anchor = create(*coverage, marker, channel);
  Image *image = anchor.image;

  mask_bake_anchor_remove(*bmain, tree(), marker, channel);
  tree().ensure_topology_cache();

  MaskBakeAnchor read;
  EXPECT_FALSE(mask_bake_anchor_read(tree(), marker, channel, read));

  bool still_present = false;
  for (Image &candidate : bmain->images) {
    if (&candidate == image) {
      still_present = true;
    }
  }
  EXPECT_FALSE(still_present);
}

/* -------------------------------------------------------------------- */
/** \name Mask Factor Bake
 *
 * The pixels B receives. #BKE_paint_material_composite_eval_row_mask is the entry the baker calls;
 * these drive it directly on hand-built image layers so the expected factor is the whole
 * expectation, with no material graph in the way.
 * \{ */

TEST_F(PaintMaterialLayerMaskBakeTest, eval_row_mask_writes_gray_rgb_alpha_one)
{
  const bUUID marker = BLI_uuid_generate_random();
  Image *mask = add_image("Mask");
  fill_image(*mask, 77, 77, 77, 255);
  Image *base = add_image("Base");
  fill_image(*base, 10, 20, 30, 255);

  PaintMaterialCompositeImageLayer layer;
  layer.marker = marker;
  layer.color_image = base;
  layer.mask_image = mask;
  layer.mask_from_alpha = false;
  Vector<PaintMaterialCompositeImageLayer> layers;
  layers.append(layer);

  ImBuf *dst = add_output_buffer();
  ASSERT_TRUE(BKE_paint_material_composite_eval_row_mask(layers, marker, dst, nullptr));
  const uchar *pixel = dst->byte_data() + (int64_t(1) * dst->x + 1) * 4;
  /* A mask is a scalar: the same gray on R, G and B, and opaque. Influence is 1, so the value is
   * the mask's own mean colour. */
  EXPECT_EQ(pixel[0], 77);
  EXPECT_EQ(pixel[1], 77);
  EXPECT_EQ(pixel[2], 77);
  EXPECT_EQ(pixel[3], 255);
}

TEST_F(PaintMaterialLayerMaskBakeTest, eval_row_mask_matches_live_composite)
{
  /* The same expression #composite_correction_pixel_mask_factor applies: a mask at 100/255, one
   * enabled Mix mask correction at half opacity toward 200/255, and a switched-off Multiply the
   * composite ignores. Mix: 100/255 + (200/255 - 100/255) * 0.5 = 150/255, so the byte is 150. */
  const bUUID marker = BLI_uuid_generate_random();
  Image *mask = add_image("Mask");
  fill_image(*mask, 100, 100, 100, 255);
  Image *base = add_image("Base");
  fill_image(*base, 10, 10, 10, 255);
  Image *mix_corr = add_image("MixCorr");
  fill_image(*mix_corr, 200, 200, 200, 255);
  Image *mul_corr = add_image("MulCorr");
  fill_image(*mul_corr, 0, 0, 0, 255);

  PaintMaterialCompositeImageLayer layer;
  layer.marker = marker;
  layer.color_image = base;
  layer.mask_image = mask;
  layer.mask_from_alpha = false;
  PaintMaterialCompositeCorrection mix;
  mix.image = mix_corr;
  mix.blend = CompositeBlend::Mix;
  mix.opacity = 0.5f;
  layer.mask_corrections.append(mix);
  PaintMaterialCompositeCorrection mul;
  mul.image = mul_corr;
  mul.blend = CompositeBlend::Multiply;
  mul.enabled = false;
  layer.mask_corrections.append(mul);

  Vector<PaintMaterialCompositeImageLayer> layers;
  layers.append(layer);

  ImBuf *dst = add_output_buffer();
  ASSERT_TRUE(BKE_paint_material_composite_eval_row_mask(layers, marker, dst, nullptr));
  const uchar *pixel = dst->byte_data() + (int64_t(1) * dst->x + 1) * 4;
  EXPECT_NEAR(pixel[0], 150, 1);
  EXPECT_EQ(pixel[3], 255);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_handles_absent_mask_corrections_only)
{
  /* A row with no map of its own in this channel: its content correction is what brings coverage,
   * which is the factor B has to hold there (spec 18 I2'). The base is transparency, so the
   * accumulated factor is the correction's own alpha. */
  const bUUID marker = BLI_uuid_generate_random();
  Image *corr = add_image("Corr");
  fill_image(*corr, 40, 40, 40, 200);

  PaintMaterialCompositeImageLayer layer;
  layer.marker = marker;
  layer.color_image = nullptr;
  layer.mask_from_alpha = true;
  PaintMaterialCompositeCorrection content;
  content.image = corr;
  content.blend = CompositeBlend::Mix;
  content.opacity = 1.0f;
  layer.content_corrections.append(content);
  Vector<PaintMaterialCompositeImageLayer> layers;
  layers.append(layer);

  ImBuf *dst = add_output_buffer();
  ASSERT_TRUE(BKE_paint_material_composite_eval_row_mask(layers, marker, dst, nullptr));
  EXPECT_EQ(dst->byte_data()[0], 200);
  EXPECT_EQ(dst->byte_data()[3], 255);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_handles_mask_disabled)
{
  /* The row's mask is off, so coverage falls back to the row's own alpha; B must hold that rather
   * than the switched-off mask's value. */
  const bUUID marker = BLI_uuid_generate_random();
  Image *base = add_image("Base");
  fill_image(*base, 10, 20, 30, 128);

  PaintMaterialCompositeImageLayer layer;
  layer.marker = marker;
  layer.color_image = base;
  layer.mask_image = nullptr;
  layer.mask_from_alpha = true;
  Vector<PaintMaterialCompositeImageLayer> layers;
  layers.append(layer);

  ImBuf *dst = add_output_buffer();
  ASSERT_TRUE(BKE_paint_material_composite_eval_row_mask(layers, marker, dst, nullptr));
  EXPECT_EQ(dst->byte_data()[0], 128);
  EXPECT_EQ(dst->byte_data()[3], 255);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_ensure_writes_row_mask_into_b)
{
  /* The whole path: a mask correction leaves an anchor and B behind, and the baker must fill B
   * with exactly what the composite reads that row's coverage as. */
  PaintMaterialLayerAddParams params;
  params.image_size = 8;
  PaintMaterialLayerEditError error = PaintMaterialLayerEditError::None;
  ASSERT_TRUE(BKE_paint_material_layer_add(*bmain, *material, params, nullptr, &error));
  ASSERT_TRUE(BKE_paint_material_layer_add(*bmain, *material, params, nullptr, &error));
  bUUID correction = {};
  ASSERT_TRUE(BKE_paint_material_layer_correction_add(*bmain,
                                                      *material,
                                                      1,
                                                      PaintMaterialCorrectionSection::Mask,
                                                      PaintMaterialCorrectionEffect::Paint,
                                                      "M",
                                                      &correction,
                                                      &error));

  Image *baked = nullptr;
  for (Image &image : bmain->images) {
    if (image.paint_layer_channel == PAINT_LAYER_MAP_MASK_BAKED) {
      baked = &image;
    }
  }
  ASSERT_NE(baked, nullptr);
  const bUUID marker = baked->paint_layer_id;

  Vector<PaintMaterialCompositeImageLayer> layers;
  ASSERT_TRUE(BKE_paint_material_composite_stack_from_material(
      *bmain, *material, PAINT_MATERIAL_CHANNEL_BASE_COLOR, layers));

  ImBuf *reference = add_output_buffer(8);
  ASSERT_TRUE(BKE_paint_material_composite_eval_row_mask(layers, marker, reference, nullptr));

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));

  void *lock = nullptr;
  ImBuf *ibuf = BKE_image_acquire_ibuf(baked, nullptr, &lock);
  ASSERT_NE(ibuf, nullptr);
  ASSERT_EQ(ibuf->x, reference->x);
  ASSERT_EQ(ibuf->y, reference->y);
  EXPECT_EQ(memcmp(ibuf->byte_data(),
                   reference->byte_data(),
                   size_t(ibuf->x) * ibuf->y * 4),
            0);
  BKE_image_release_ibuf(baked, ibuf, lock);
}

/* -------------------------------------------------------------------- */
/** \name Bake Cache
 *
 * The lazy half of the baker: a second ensure with nothing changed does no work, and every kind of
 * change -- the graph's description, a source image's pixels, an explicit invalidation -- brings a
 * rebuild back.
 * \{ */

TEST_F(PaintMaterialLayerMaskBakeTest, bake_cache_skips_when_clean)
{
  const BakedRow row = build_baked_row();
  ASSERT_NE(row.baked, nullptr);
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  const uint64_t first_revision = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  EXPECT_NE(first_revision, 0u);
  EXPECT_TRUE(BKE_paint_material_mask_bake_cache_contains(*material, row.row_marker, channel));

  /* A sentinel the bake cannot produce. Writing it marks no partial update, so only the cache's own
   * dirty state can cause a rewrite; if it does rewrite, the sentinel is gone. */
  fill_image(*row.baked, 17, 17, 17, 255);
  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_EQ(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            first_revision);
  uchar pixel[4] = {0, 0, 0, 0};
  read_pixel(*row.baked, 0, 0, pixel);
  EXPECT_EQ(pixel[0], 17);
  EXPECT_EQ(pixel[3], 255);

  /* Forcing a full rebuild is the way past a clean cache, and it does overwrite the sentinel. */
  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  EXPECT_NE(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            first_revision);
  read_pixel(*row.baked, 0, 0, pixel);
  EXPECT_NE(pixel[0], 17);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_cache_recomputes_on_structural_change)
{
  const BakedRow row = build_baked_row();
  ASSERT_NE(row.baked, nullptr);
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  const uint64_t first_revision = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  ASSERT_NE(first_revision, 0u);

  /* Muted directly rather than through the edit API: no commit runs, so the explicit invalidation
   * a public edit would also raise cannot be what rebuilds B. The cache's own structural hash is
   * the only thing that can notice the factor changed. */
  bNode *node = correction_node(row.correction);
  ASSERT_NE(node, nullptr);
  node->flag |= NODE_MUTED;

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_NE(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            first_revision);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_cache_recomputes_on_pixel_change)
{
  const BakedRow row = build_baked_row();
  ASSERT_NE(row.baked, nullptr);
  Image *correction = correction_image(row.correction);
  ASSERT_NE(correction, nullptr);
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  const uint64_t first_revision = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  ASSERT_NE(first_revision, 0u);

  uchar before[4] = {0, 0, 0, 0};
  read_pixel(*row.baked, 0, 0, before);

  /* A dab on the correction's map, recorded the way the paint path records one; the cache learns
   * about it by polling, with nothing told to it. */
  rcti dab;
  BLI_rcti_init(&dab, 0, 2, 0, 2);
  paint_region(*correction, dab, 200);

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_NE(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            first_revision);

  uchar after[4] = {0, 0, 0, 0};
  read_pixel(*row.baked, 0, 0, after);
  EXPECT_NE(memcmp(before, after, sizeof(after)), 0);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_cache_invalidate_marks_dirty)
{
  const BakedRow row = build_baked_row();
  ASSERT_NE(row.baked, nullptr);
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  const uint64_t first_revision = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  ASSERT_NE(first_revision, 0u);

  /* Marked, not dropped: the entry survives so a reader in between keeps its pixels. */
  BKE_paint_material_mask_bake_cache_invalidate(material);
  EXPECT_TRUE(BKE_paint_material_mask_bake_cache_contains(*material, row.row_marker, channel));
  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  const uint64_t second_revision = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  EXPECT_NE(second_revision, first_revision);

  /* The null form is the undo path: every material's entries go dirty at once. */
  BKE_paint_material_mask_bake_cache_invalidate(nullptr);
  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_NE(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            second_revision);

  /* Dropping is the other half: the entry is gone, and the next ensure rebuilds from scratch. */
  BKE_paint_material_mask_bake_cache_free_material(*material);
  EXPECT_FALSE(BKE_paint_material_mask_bake_cache_contains(*material, row.row_marker, channel));
  EXPECT_EQ(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel), 0u);
}

TEST_F(PaintMaterialLayerMaskBakeTest, bake_cache_revision_changes_only_when_written)
{
  const BakedRow row = build_baked_row();
  ASSERT_NE(row.baked, nullptr);
  const int channel = PAINT_MATERIAL_CHANNEL_BASE_COLOR;

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  const uint64_t written = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  ASSERT_NE(written, 0u);

  /* Reads that write nothing must not move the revision: a consumer uses it to tell whether its
   * copy of B is still current, and a needless bump would force an upload for nothing. */
  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_EQ(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            written);
  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_EQ(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            written);

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, true));
  const uint64_t rewritten = BKE_paint_material_mask_bake_cache_revision(
      *material, row.row_marker, channel);
  EXPECT_NE(rewritten, written);

  ASSERT_TRUE(BKE_paint_material_mask_bake_ensure(*bmain, *material, false));
  EXPECT_EQ(BKE_paint_material_mask_bake_cache_revision(*material, row.row_marker, channel),
            rewritten);
}

/** \} */

}  // namespace blender::bke::tests
